### ISSUE TITLE
Go live checklist

### ISSUE THREAD

**Issue by mperham** [mperham/inspeqtor#3]
I'm hoping to launch Inspeqtor next week!!1!!one11!  So EXCITED!
# TODO
- [x] Finish initial OSS functionality
- [x] Finish initial Pro functionality
- [x] Wiki documentation
- [x] OSS distribution via packagecloud.io
- [x] Pro distribution
- [x] Pro license
- [x] Finish website design
- [x] Push website code to github
- [x] Merge website code into gh-pages so it goes live
- [x] Finish announcement blog post
- [x] Push final 0.5.0 binaries to packagecloud
